# Generated by Django 5.1.4 on 2024-12-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expense_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='expense_photos/'),
        ),
    ]
