# Generated by Django 5.1.4 on 2024-12-16 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 16, 16, 17, 28, 956663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=12),
        ),
    ]
