# Generated by Django 5.1.4 on 2024-12-16 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_budget_date_budget_year_alter_budget_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 16, 16, 17, 35, 693176, tzinfo=datetime.timezone.utc)),
        ),
    ]
